### ISSUE TITLE
Review the Designspace 

### ISSUE THREAD

**Issue by vv-monsalve** [SophiaDesign/Foldit#3]
What is the intended designspace for the font?

### Masters
Inspecting the current source file, it goes from a visually extra-condensed (named `Condensed` in the file) Thin extreme to an Expanded ExtraBold one, but there are only two masters to govern that wide range.

<img width="668" alt="Screen Shot 2022-04-07 at 9 47 52" src="https://user-images.githubusercontent.com/48698976/162238489-3bb04e42-29c0-47bd-8af8-fb8acd875bf4.png">

You would need at least another master located at the Regular weight, Normal width to better administrate the variations.

### Instances

On the other hand, plan ahead and carefully manage which would be all the intermediate instances considering both the currently supported [fvar instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances) as well as that the API will generate all the possible [static instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#instantiated-static-fonts) within a range.

It's not entirely clear why there are duplicate instances now. This could be related to the reported [export issues](https://github.com/SophiaDesign/GF-Foldit/issues/2).

<img width="928" alt="Screen Shot 2022-04-07 at 9 47 12" src="https://user-images.githubusercontent.com/48698976/162247439-68cd22a1-2164-447d-ae16-026ab702c38f.png">

A good case of reference would be [Archivo](https://fonts.google.com/specimen/Archivo?vfaxis=wdth#about)

**Comment by SophiaDesign** [comment]
Current project scope is for 2 masters and combined axis of weight and width, but defined with only `wght` to work with existing systems. There is option to extend design space further @davelab6

For now I close this issue.

**Comment by vv-monsalve** [comment]
@SophiaDesign please remember to include the required **instances** (or exports) for the `wght` axis as we talked about in our last meeting. 

This is related to what was said in some comments above

> > On the other hand, plan ahead and carefully manage which would be all the intermediate instances considering both the currently supported [fvar instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances) as well as that the API will generate all the possible [static instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#instantiated-static-fonts) within a range.
> 
> Please note that you would need to add the instances to be accessed through the fvar table. Also, by default the API will generate all the possible static instances within a range being they declared in the source file or not. Please give the above links a careful review. Thanks.

Reopening this issue until the instances are solved.

**Comment by SophiaDesign** [comment]
The instances have been defined in Glyphs:
- Thin
- Light
- Regular
- Medium
- SemiBold
- Bold
- Extrabold
- Black

Is anything else needed for adding the fvar table? I added an axis mapping to the var instance (Glyph exports) and can add the instances in config.yaml once the static exports with `gftools` are working @vv-monsalve

**Comment by vv-monsalve** [comment]
> 2 masters and combined axis of weight and width, but defined with only wght to work with existing systems

Given the nature of your project, the `Width Class` of your instances should only be `Medium (normal) (5)`

As mentioned in our meeting, you could check up on [Syne](https://fonts.google.com/specimen/Syne) font as a reference for a similar case.

Since the Axes Coordinates Weight values of your masters are already using the user `usWeightClass` values, an axis mapping will not be needed. You would like to read the content about the [Axis Mapping](https://googlefonts.github.io/gf-guide/variable.html#the-axis-mapping) custom parameter under the [Variable Font](https://googlefonts.github.io/gf-guide/variable.html) chapter of our documentation to have more details on this.

I've also seen that the last source file includes too many new masters. Did you find the need to add them for any particular reason? Typically it is not suggested to have many masters to avoid increasing file size and to make it easier to administrate and maintain your project.

**Comment by SophiaDesign** [comment]
@vv-monsalve I added the instances to have the visually correct weights correspond to the numbers in these [static instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#instantiated-static-fonts) and [fvar instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances) tables. Alternatively I can remove the instances/masters and just edit the axis map accordingly for the variable font.

Which would work better technically? Or if there's a method that is better than both, let me know?

**Comment by vv-monsalve** [comment]
> ...or I can remove just the instances and keep the masters, if that would work?

It is actually the opposite. You would need only a couple of masters, and all the instances (exports) to rule the desired fvar instances + instantiated static fonts.

> @vv-monsalve I added the instances to have the visually correct weights correspond to the numbers in these [static instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#instantiated-static-fonts) and [fvar instances](https://github.com/googlefonts/gf-docs/tree/main/Spec#fvar-instances) tables.

this is ok

**Comment by vv-monsalve** [comment]
@SophiaDesign After pulling the latest files at commit ee26e203bf4f737393942c4a61f659a17dc21a83 There are still too many masters for the project. 

> Typically it is not suggested to have many masters to avoid increasing file size and to make it easier to administrate and maintain your project.

Please keep only the Thin, Regular (for it to be the Variable font origin), and Black masters. You would like to read the Glyphs chapter about [Masters and Instances](https://glyphsapp.com/learn/multiple-masters-part-1-setting-up-masters) to have more details on their differences. 

Reducing the number of masters is of great help to better administrate the project, e.g. checking/solving [Won gradients issue reported](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1206655375).
