### ISSUE TITLE
COLRv1 variable format export issue

### ISSUE THREAD

**Issue by SophiaDesign** [SophiaDesign/Foldit#6]
_Context:_ 
It was possible to export a variable font with COLRv1 gradient (gradient was non-variable) using `fontmake` first on [11th April 2022](https://github.com/SophiaDesign/GF-Foldit/issues/2#issuecomment-1095408509). 

_Since 25 May 2022:_ 
Issue exporting gradient for COLRv1 variable font. Only black version appears now. Current versions are `fontmake 3.3.0` and `gftools 0.9.11` and exports are made locally in terminal on MacOS. 

I am getting the following error from using either `fontmake` and `gftools` on any of the "decomposed" glyphs files dating back to the 11th April version which previously worked (30th May):
> fontmake.errors.FontmakeError: In 'GF-Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: module 'uharfbuzz' has no attribute 'RepackerError'

@khaledhosny is harfbuzz/fontmake working okay for you?

From here on Github Actions should be ignored and exports are to be made locally using `gftools`. Variable font export showing gradients worked on 26 May 2022 for @vv-monsalve
-- Viviana, could you confirm which version `gftools` you used and which sourcefile (last modified date and time)?
-- p.s. I am still not getting them exported into a "fonts" folder, even when using gftools. Could it have anything to do with my MacOS (Catalina version 10.15.7)?

**Comment by khaledhosny** [comment]
> @khaledhosny is harfbuzz/fontmake working okay for you?

Looks like you updated fonttools without also updating uharfbuzz, updating uharfbuzz should fix this error.

**Comment by vv-monsalve** [comment]
> -- Viviana, could you confirm which version gftools you used and which sourcefile (last modified date and time)?

On our meeting that day, we performed different attempts at producing the font to compare the results:

1. Exporting the font directly from Glyphs (using the `Variable` instance present in the file) produced a font named `Foldit-variableVF.ttf` with visible gradients on preview.
2. Exporting the font directly from Glyphs (without the `Variable` instance) which produced a font named `FolditVF.ttf` with no gradients.
3. Compiling the font using Builder, which produced the font `Foldit[COLR,wght].ttf` with no gradients. It was produced under a venv with `gftools 0.8.2` and `Fontmake 2.4.1`

The source file used was the same under sources dir [GF-Foldit-decomposed.glyphs](https://github.com/SophiaDesign/Foldit/blob/main/sources/GF-Foldit-decomposed.glyphs) just renamed to `Foldit.glyphs` + an updated config using it.

All the files are attached here.

[May-26.zip](https://github.com/SophiaDesign/Foldit/files/8806996/May-26.zip)

**Comment by vv-monsalve** [comment]
> -- p.s. I am still not getting them exported into a "fonts" folder, even when using gftools. Could it have anything to do with my MacOS (Catalina version 10.15.7)?

Not even locally? Remember that you would need to add and push the files for them to appear on this repo, otherwise, they will remain local.

Which command did you use?

**Comment by SophiaDesign** [comment]
Thanks @vv-monsalve @khaledhosny updating to `uharfbuzz 0.26.0` solved the export issue. I am using `gftools builder` in MacOS terminal to export directly from a Glyphs file.

**Comment by SophiaDesign** [comment]
> On our meeting that day, we performed different attempts at producing the font to compare the results:
> 
> 1. Exporting the font directly from Glyphs (using the `Variable` instance present in the file) produced a font named `Foldit-variableVF.ttf` with visible gradients on preview.
> 2. Exporting the font directly from Glyphs (without the variable instance) produced a font named `FolditVF.ttf` with no gradients.
> 3. Compiling the font using Builder, which produced the font `Foldit[COLR,wght].ttf` with no gradients. It was produced under a venv with `gftools 0.8.2` and `Fontmake 2.4.1`
> 
> The source file used was the same under sources dir [GF-Foldit-decomposed.glyphs](https://github.com/SophiaDesign/Foldit/blob/main/sources/GF-Foldit-decomposed.glyphs) just renamed to `Foldit.glyphs` + an updated config using it.
> 
> All the files are attached here.
> 
> [May-26.zip](https://github.com/SophiaDesign/Foldit/files/8806996/May-26.zip)


Something peculiar we found was the axis changed at different pace when using `gftools builder` compared to `Glyphs app export`.
1. is an OpenType SVG font (but also variable?)
2. is a variable font without color feature
3. should be a COLRv1 variable font -- we also got a version with visible gradient (after recording the video below)

https://user-images.githubusercontent.com/84964395/171236565-4665d4f1-796a-4430-b369-b823dc9f9698.mp4

**Comment by khaledhosny** [comment]
> * Exporting the font directly from Glyphs (using the `Variable` instance present in the file) produced a font named `Foldit-variableVF.ttf` with visible gradients on preview.

Glyphs does not support COLRv1 table yet, so what you are seeing must be SVG table and this can’t be variable at all. `Foldit-variableVF.ttf` indeed has an `SVG` table and no `COLR` or `CPAL` tables.

> * Exporting the font directly from Glyphs (without the variable instance) produced a font named `FolditVF.ttf` with no gradients.

That is probably because the variable instance has `Color Layers to SVG` custom parameter and without it Glyphs does not export an SVG table, and indeed `FolditVF.ttf` has no `SVG` or other color tables.

> * Compiling the font using Builder, which produced the font `Foldit[COLR,wght].ttf` with no gradients. It was produced under a venv with `gftools 0.8.2` and `Fontmake 2.4.1`

To get `COLR` table from Glyphs color layers you need `glyphsLib >= 6.0.0`.

**Comment by khaledhosny** [comment]
Currently FontTools‘ varLib (which is responsible for merging masters into variable fonts) does not support `COLR` table, so even if you get a variable font with `COLR` the color data will not be variable. It looks like that @anthrotype started work on this https://github.com/fonttools/fonttools/tree/wip-variable-colr but I think he is on a leave now.

**Comment by vv-monsalve** [comment]
> To get COLR table from Glyphs color layers you need glyphsLib >= 6.0.0.

Thank you @khaledhosny for the clarifications. The first two points match our reasonings on it but were not aware of the third. So I was unsure why there was no `COLR` table on it.
